### ISSUE TITLE
Fatal error: Call to undefined method Enterprise_Mview_Model_Client::initByTableName()

### ISSUE THREAD

**Issue by rodrigowebjump** [AOEpeople/Aoe_EeIndexerStats#2]
Hi,

I am receiving a fatal error when try to perform any action

Fatal error: Call to undefined method Enterprise_Mview_Model_Client::initByTableName() in 
/app/code/community/Aoe/EeIndexerStats/controllers/Adminhtml/ProcessController.php on line 12

We are using Enterprise 1.14.1.0

**Comment by rodrigowebjump** [comment]
The method initByTableName is only available on 1.14.2.0.

**Comment by LeeSaferite** [comment]
Fixed in PR #5
